### ISSUE TITLE
How i can destroy all widgets?

### ISSUE THREAD

**Issue by anorudes** [uploadcare/uploadcare-widget#331] opened 2016-04-08 09:39 UTC
Hello, can you help me with destroy all widgets?

I want make this:
uploadcare.remove('body');
uploadcare.initialize('body');

or
uploadcare.reset('body');

**Comment by dmitry-mukhin** [comment] 2016-04-08 13:15
is this a #328 duplicate?

**Comment by nd0ut** [comment] 2018-05-03 11:51
Duplicate of https://github.com/uploadcare/uploadcare-widget/issues/328

**Closed by nd0ut** 2018-05-03 11:51 UTC
Labels: duplicate
