### ISSUE TITLE
Exception when canceling upload

### ISSUE THREAD

**Issue by pozadi** [uploadcare/uploadcare-widget#215] opened 2015-03-27 19:53 UTC
Hi, I am having an exception from this line https://github.com/uploadcare/uploadcare-widget/blob/abee13cc6957264e1e59fa4c2e1dfe225014a822/app/assets/javascripts/uploadcare/files/object.js.coffee#L25 saying "Cannot read property 'size' of undefined".

We are calling `file.cancel()` in our app code when this exception is thrown.

**Comment by homm** [comment] 2015-03-27 21:49
I can't reproduce. I'm trying to cancel uploading in different moment after start (from 0 to 2000ms) and nothing leads to the exception. http://jsbin.com/keqawe/1/watch?js,output

Please also check you are using latest 2.0.5 widget version.

**Comment by homm** [comment] 2015-03-28 10:17
Fixed in [v2.0.6](https://github.com/uploadcare/uploadcare-widget/tree/v2.0.6). Thank you!

**Closed by homm** 2015-03-28 10:17 UTC

**Comment by pozadi** [comment] 2015-03-28 10:49
:+1:
