### ISSUE TITLE
Do not demand on elements order in DOM in mobile layout

### ISSUE THREAD

**Issue by d4nyll** [uploadcare/uploadcare-widget#265] opened 2015-09-21 13:36 UTC
Hi,

I've been trying out your widget for a client of mine. On my Chrome on Ubuntu, when I resize my screen to below 761px and then click 'Choose an image', the widget will pop up momentarily, and then the entire screen goes blank.

So for 761px or above, all is well.

![](http://i.imgur.com/v1Jb8e4.png)

Then for 760px or below, the 'correct' user interface pops up for a moment (maybe half a second?)

![](http://i.imgur.com/FeFvd3p.png)

After which the entire screen goes blank.

![](http://i.imgur.com/RNtXJNh.png)

I've tried to reproduce this on my mobile (Android LG Optimus G Pro - http://www.lg.com/in/mobile-phones/lg-Optimus-G-Pro-E988-mobile-phones) and an iPhone 6, as well as Chrome on OSX and they work fine. It's only on my Chrome on Ubuntu where this occurs.

This is my browser user agent string: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36`

**Comment by homm** [comment] 2015-09-21 13:40
Could you take a screenshot of DOM tree with first level children of `body` elements?

**Comment by d4nyll** [comment] 2015-09-21 14:00
Yep! Here you go.

![](http://i.imgur.com/cTtpMLg.png)

**Comment by homm** [comment] 2015-09-21 14:15
Thank you. Looks like some of your browser extensions adds `<script>` as the last child of body. Current widget implementation demands on the fact that the last child of `<body>` should be the last opened dialog. As I see this is not works in your case, and I'll try to fix it.

The good news is you can't reproduce this on the real mobile devices because mobile browsers in common don't allow install browser extensions. But this still should be fixed.

**Closed** 2015-09-22 17:27 UTC
